name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of deployed site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "APP_TOKEN=${{ secrets.APP_TOKEN }}" > .env
          echo "NODE_ENV=production" >> .env

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: 'production'

      - name: Check if dist folder exists
        run: |
          ls -alh dist  # Confirm if dist folder exists after build

      - name: Debug dist folder contents
        run: |
          ls -R dist  # List all files in the dist folder recursively

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload the build output as an artifact for GitHub Pages
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Make sure this path points to the correct build folder

      - name: Wait for artifact to be available
        run: sleep 10  # Add a small delay to ensure the artifact is available

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages  # Use the same name as your uploaded artifact