name: Deploy static content to Pages

on:
  push:
    branches: ['main']  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

# Set permissions for the GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of deployed site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Create the .env file dynamically
      - name: Create .env file
        run: |
          echo "REMOTE_ENDPOINT=${{ secrets.REMOTE_ENDPOINT }}" >> .env
          echo "APP_TOKEN=${{ secrets.APP_TOKEN }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Build project
        run: npm run build
        env:
          REACT_APP_REMOTE_ENDPOINT: ${{ secrets.REACT_APP_REMOTE_ENDPOINT }}
          REACT_APP_APP_TOKEN: ${{ secrets.REACT_APP_APP_TOKEN }}
          NODE_ENV: 'production'  # Ensure production environment for build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'  # Path to the directory where the build output is

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
