name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "APP_TOKEN=${{ secrets.APP_TOKEN }}" > .env
          echo "NODE_ENV=production" >> .env

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: 'production'

      - name: Check if dist folder exists
        run: |
          ls -alh dist  # Confirm if dist folder exists after build

      - name: Debug dist folder contents
        run: |
          ls -R dist  # List all files in the dist folder recursively

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Path to the build output
          publish_branch: gh-pages  # Branch to deploy to